language: node_js
node_js:
  - "node"
  - "8.3"
  - "10"
  - "12"
before_script: >
  node_version=$(node -v);
  if [ ${node_version:3:1} = "." ]; then
    echo "Node 10+"
    else
      echo "Node 8"
      npm install --no-save "eslint@5"
  fi
script:
  - npm run test
